### ISSUE TITLE
Mailchimp Newsletter

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#112]
Brian -

Can I get a quick image for https://us17.admin.mailchimp.com/templates/edit?id=92721
The purpose of this template is a monthly newsletter to StatEngine users.  I would like to reusue the template month to month.  Feel free to do any styling to the base template. 

1.  Replace getting started header with a generic newsletter banner.
2.  Images for the rest of the content.  I wrote the text and the three topics I would like to discuss in the first newsletter.  Do you have nice screenshots/mockups of the reporting or twitter? Let me know what you think....

**Comment by bingles** [comment]
Hey @chopchop505, the MC "SE Newsletter" template has been updated, tested and should now render in email clients per the design below:

![newsletter](https://user-images.githubusercontent.com/636170/44152505-b876198c-a073-11e8-9d7f-77af4f3ffc94.png)
