### ISSUE TITLE
Generic framework and theme styling cleanup

### ISSUE THREAD

**Issue by bingles** [StatEngine/stat-engine#117]
Identified areas in need of attention:

### Unauthenticated
- [x] Homepage and Subpages
- [x] Login, Signup & Reset

### Authenticated
- [x] Header Panel
- [x] Sidebar Navigation
- [x] Breadcrumbs (First styling pass made. @chopchop505 to hook up functionality)
- [x] Main Panel (content) Templates
- [x] Components: Icons, Cards, Buttons, Typography

#### Pages/Views:
- [x] User Home/Control Center
- [x] Marketplace
- [x] Reports > Incident Analysis
- [x] Settings
- [x] Setttings > My Profile

#### Generic:
- [x] Form Validation (@chopchop505 to review)

**Comment by bingles** [comment]
@chopchop505 Could we implement functionality to the sidebar that adds an active state (a CSS class of "active") to the selected menu item?  Currently, the closest thing to that we have is the sub-menu drawer open state:

<img width="66" alt="sidebar" src="https://user-images.githubusercontent.com/636170/45267323-1559e980-b41f-11e8-9c14-2a2d3f9fa811.png">

**Comment by bingles** [comment]
Hey @chopchop505, I've got this in pretty good shape at this point and the only remaining clean up from a "first pass" standpoint is the Incident Analysis/Summary view. Lets chat when you get a minute!

**Comment by chopchop505** [comment]
@bingles - please pull - I've been making updates

Can you take
- [ ]  incident analysis page
- [ ] twitter application page

![image](https://user-images.githubusercontent.com/32108478/46559811-2dd9ea00-c88d-11e8-8bcc-50580f8b70ac.png)

**Comment by bingles** [comment]
@chopchop505 Still need to tackle the Twitter application page, but the incident analysis should be good to go with the exception of the plot.ly visualizations on smaller resolutions. I have spent a little time trying to diagnose and have tried setting the config to `{ responsive: true }` per the docs [here](https://plot.ly/javascript/responsive-fluid-layout/), but it doesn't seem to work correctly. Maybe we can tag up in regards to this?
