### ISSUE TITLE
Extra left margin in Reports/Units page.

### ISSUE THREAD

**Issue by larskendall** [StatEngine/stat-engine#133]
I must have gotten a false positive when testing my initial fix for the sidenav overlap issue. There's no some extra space on the left next to the sidenav.

![Screen Shot 2019-01-17 at 9.09.03 PM.png](https://images.zenhubusercontent.com/5c3fa1fb200b6654c1aa9742/1d72b577-cf14-43c3-9c8a-4f7eb48c0265)

**Comment by chopchop505** [comment]
Deployed - thanks @larskendall
