### ISSUE TITLE
Add content to "Our Partners"

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#28]

**Comment by garnertb** [comment]
Partners are:

* [NFORS](nfors.org)
![nfors_logo 55c4d081c5625](https://user-images.githubusercontent.com/1141646/32789080-e735c330-c928-11e7-86b5-24e04c759060.jpg)

* [Richmond Fire Department](http://www.richmondgov.com/Fire/index.aspx)
![pasted image at 2017_09_27 04_21 pm](https://user-images.githubusercontent.com/1141646/32789011-be5cb572-c928-11e7-8f46-ccd08d5e40c4.png)

* [Hanover Fire & EMS](https://www.hanovercounty.gov/297/Fire-EMS)
![pasted image at 2017_09_27 04_19 pm](https://user-images.githubusercontent.com/1141646/32789010-be3fe3a2-c928-11e7-99a9-edaa707d3db6.png)


@bingles can you provide guidance on the size/color of these?

**Comment by bingles** [comment]
Hey guys, attached is the mock of this section as well as the individual logo assets. They have already been optimized. Let me know if there is anything else needed! 

**Mock**
<img width="1135" alt="our-partners-mock" src="https://user-images.githubusercontent.com/636170/32793037-d3626a98-c932-11e7-8e68-ac59d587d48e.png">


**Assets**
![partner-hanover-fd](https://user-images.githubusercontent.com/636170/32792994-c1682882-c932-11e7-8ef4-8b940648b255.png)
![partner-nfors](https://user-images.githubusercontent.com/636170/32792995-c17660a0-c932-11e7-9ddb-c37e77754d4d.png)
![partner-richmond-fd](https://user-images.githubusercontent.com/636170/32792996-c198bdd0-c932-11e7-88c9-c590474171d7.png)
