### ISSUE TITLE
Dashboard sidebar item isn't shown as active on Workspaces page

### ISSUE THREAD

**Issue by larskendall** [StatEngine/stat-engine#309]
![Screen Shot 2019-07-16 at 8.07.45 PM.png](https://images.zenhubusercontent.com/5c3fa1fb200b6654c1aa9742/5cce96e4-c242-4710-81ed-6cc704706d9f)

**Comment by vbence86** [comment]
The exact same behaviour can be seen with all menu items if you click randomly anywhere on the screen. What is the expected behaviour here @larskendall @chopchop505 ?

**Comment by chopchop505** [comment]
@vbence86 

![image](https://user-images.githubusercontent.com/32108478/64310997-23611e00-cf3e-11e9-997d-badd5f5ecbe7.png)

**Comment by chopchop505** [comment]
The intent is to show the little blue bar when on the page.
