### ISSUE TITLE
As a department admin, I should be able to create accounts on behalf of other users

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#330]
The current signup workflow is:
- user signups for an account, and requests access to a Fire Department
- department admins receive an email regarding the request
- either through email click or access the webapp, the department admin approve/rejects access

Multiple departments have requested the ability to create accounts on behalf of their users.  A new workflow could look like this:
- department admin navigates to department admin page and clicks a button to add a new user
- department admin fills out signup form.  The signup form will be similar to the current form, but fields such as password and requested fire department should be hidden/removed.
- on submit, we create the user with an autogenerated password and assign the fire department automatically
- we send an email to new user with welcome message, sign-in, and change passowrd instructions 

@larskendall @vbence86 thoughts?

**Comment by vbence86** [comment]
It looks like a very straightforward process that our clients should be happy with, so +1 from me.
