### ISSUE TITLE
Sort units in sidebar on units report page

### ISSUE THREAD

**Issue by andersonad** [StatEngine/stat-engine#343]
At present we perform no sorting on the units in the left sidebar, this makes it difficult to find a unit without resorting to searching for it. One suggestion is alphabetical. We don't give any information aside from the unit name so it might be best to sort them alphabetically/numerically so it's clear how to scroll through them looking for your units.

![Screenshot from 2019-10-01 14-59-40](https://user-images.githubusercontent.com/12083964/65996238-a94c8800-e45c-11e9-89b7-87032764c3d0.png)

**Comment by chopchop505** [comment]
There are sorted by busiest unit

**Comment by chopchop505** [comment]
I think we could add a sort by drop down (sort by business, alphabetically)

**Comment by andersonad** [comment]
I checked with San Francisco and it doesn't seem to be sorted by total responses nor by total commitment time? Am I missing something?

**Comment by chopchop505** [comment]
Its sorted by total responses (all time), which to your point - is not clear to the user.
You can verify the order by hitting: https://statengine.io/api/units.

I think we could add the option to sort alphabetically easily

**Comment by andersonad** [comment]
Ah, go figure. Unfortunately 1 year back is as far as the report goes so I don't think the user would be able to uncover that. 

Alphabetical sort option, put it on the nice-to-have pile!
