### ISSUE TITLE
Add icons to Features section

### ISSUE THREAD

**Issue by bingles** [StatEngine/stat-engine#37]
**Mock Up**
![features](https://user-images.githubusercontent.com/636170/32793345-ae1cd2fe-c933-11e7-8d5b-e9149559b9ae.png)

**Assets** 
SVGs have been added to the `"client/assets/images/icon-"` path.

**Comment by garnertb** [comment]
@bingles, do you have cycles to help implement this?

**Comment by bingles** [comment]
Sure! It might not be until another week or so due to the house move, but I'll see if I can knock it out this week/weekend. Is that ok?

**Comment by garnertb** [comment]
Yep, thanks!
