### ISSUE TITLE
SPADE Ingest API

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#44]
I've been going through some design cycles regarding SPADE to StatEngine ingest API. 
I first structured it REST style with HTTP verbs, where spade would PUT (for upsert) or DELETE: 

**Option 1.**
`PUT https://statengine.io/api/ingest/fire-incident?fd_id=76000?name=incident123456`
`DELETE https://statengine.io/api/ingest/fire-incident?fd_id=76000?name=incident123456`

That being said, it probably makes SPADE's life easier to simply post to one endpoint and not have to worry about the verb or type when constructing the endpoint.  So I've convinced my self this might be a better option:

**Option 2.**
`POST https://statengine.io/api/ingest?fd_id=76000`

The query param in the POST is not strictly necessary, but makes it simpler to integrate with AWS lamba authorizers (for gw requests) down the road.

The body content would be a structured message, that describes the ingest request.  Something similar to
```
{
  id: incident12345,
  fd_id: 7600,
  type: 'fire-incident',
  action: update || delete
  payload: '..........'
}
```

Regarding Content-Type and encoding, we should probably use protobuf or something similar. This would dramatically cut our AWS ingest costs down when going through api, and makes structuring and parsing the wrapped message simple.

Regarding authorization, Basic Auth over SSL should suffice and is nice because SPADE can make just a single request without dealing with tokens or expirations.  However, this would require on-premise stat-engine to be on https to be secure. 

Thoughts?

@garnertb @smesdaghi

**Comment by garnertb** [comment]
Right now, we don't really have a use-case where spade can delete.  Only upserts are supported so far.

What do you think about changing the query params into hierarchal url params to enable future routes to be implemented?

Something like this:
`POST /api/departments/<id>/incidents/ingest`.

Then in the future we could enable the department api route at:
`GET /api/departments/<id>`.

Then I'd think we could eliminate most of the body of the request besides the actual payload.  I'm fine with either proto or JSON for the content-type.

**Comment by chopchop505** [comment]
That approach is definitely closer to REST.  Will SPADE have the concept of ids/names? If so, then it should probably be:

PUT `/api/departments/<fd_id>/incidents/<id>`

The only downsides I see with it being more statically written: 

- I was envinsioning entirely disabling (not mounting) the ingest routes on stat-engine unless on-premise.  Organizing them in your suggested fashion (where `GET` on /api/departments/<fd_id>/ might be enabled but `POST `/api/departments/<fd_id>/incidents/ingest` is disabled, makes it less clean. That being said, we could just add a middleware guard.
- The Amazon GW API should match our internal api. SPADE shouldn't be configured differently if talking to stat-engine cloud or stat-engine on-premise.  So that implies more to manage in AWS land (we add a new incident type or route, we need to add a new path in amazon), but should be doable.
