### ISSUE TITLE
Move-up Model MVP

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#443]
## Overview
A "move-up" occurs when a fire department reallocates apparatus to different stations due to changes in call volume.  For example, a move up might occur when MEDIC1, normally parked at Station 1, is moved to Station 2 because of high-call volume at Station 2. 

Our research team has developed an algorithm to optimize a move-up strategy.  

My suggested steps for implementation

- [ ] The algorithm currently lives in Python code [https://github.com/FireCARES/research/tree/master/move_up_model](https://github.com/FireCARES/research/tree/master/move_up_model).  Since our codebase is in Javascript, and we have plenty of code as Serverless - I would suggest we package this code as an AWS function in the Serverless framework.    Something like this: https://github.com/ProminentEdge/se-lambda-enrichment-mesa-az/blob/master/handler.js
- [ ] The proposed model input is: 
```
{
    "covered_time": 4,
    "unit_status": [
        {
            "unit_id": "E15",
            "current_location": "dq8vwnz9hnnf",
            "status": "AVAILABLE"
        },
        {
            "unit_id": "E22",
            "current_location": "dq8vhzty3460",
            "status": "AVAILABLE"
        },
      .....
    ],
    "station_status": [
        {
            "station_id": 10,
            "location": "dq8vtmdf890v"
        },
        {
            "station_id": 11,
            "location": "dq8vw99k32nc"
        },
      ....
    ],
    "incident_distribution": [
        "dq8vmzh1u8xp",
        "dq8vkvpxt6xs",
        "dq8ve9xfz7bx",
        ...
    ]
}
```
- [ ] The proposed model output is: 
```
{
    "current": {
        "metrics": {
            "percentage_under_4_minute_travel": 74.7
        }
    },
    "move_up": {
        "strategy": "maximize fraction of incidents within 4 minute travel time",
        "metrics": {
            "percentage_under_4_minute_travel": 86.4
        },
        "moves": [
            {
                "unit_id": "E14",
                "station": 16
            },
            {
                "unit_id": "E8",
                "station": 17
            },
            {
                "unit_id": "E25",
                "station": 23
            },
            {
                "unit_id": "E19",
                "station": 20
            },
            {
                "unit_id": "E6",
                "station": 5
            }
        ]
    }
}
```

Because the model input requires station data, we will probably have to make use of Firecares APIS to determine the geohashes of stations. 

As a proxy, the incident distribution can just be a query for the last 1000 incidents.  

## Acceptance Criteria
The user should be able to input 
- [ ] the desired covered time.
- [ ] each unit status (AVAILABLE/UNAVAILABLE), and the current location 

After running the model, the user should see the desired moves and the percent improvement.  
Possible displays:

![image](https://user-images.githubusercontent.com/32108478/78711777-3e6c8580-78b3-11ea-82a8-e7e439fcb2c3.png)

 
## Mockups / Screenshots
 To be supplied after discussion with Luca and Bingles.

## Charge code/budget
To be supplied, in the meantime charge IPSDI 8B with note

# Outstanding Questions
1.  @garnertb I think the move up model should live in Firecares if Tyler B will be tweaking it.  Can we get Luca write access to Firecares.  
2.  @bingles I will schedule a brainstorming session for UI

**Comment by chopchop505** [comment]
@bingles This was another visual we experimented with 

![move_up_example0](https://user-images.githubusercontent.com/32108478/78827574-00d52e80-797f-11ea-8d81-98a8bb0d1e6a.png)

**Comment by bingles** [comment]
@chopchop505 I really like the concept of showing the original location of the apparatus, but find all the colors a bit overwhelming. I think a hybrid approach might be nice. I'm exploring some options now! 💪🏽
