### ISSUE TITLE
Update move-up model drive polygons to use Mapbox isochrones 

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#471]
## Overview

The model has been updated to use Mapbox isochronse, we should aslo update the frontend: https://www.google.com/search?q=Mapbox+isochrones&oq=Mapbox+isochrones&aqs=chrome..69i57j0.1041j0j4&sourceid=chrome&ie=UTF-8

## Acceptance Criteria
-

**Comment by bliitzkrieg** [comment]
Waiting on Tyler to implement a fix to Move Up Model
