### ISSUE TITLE
Move up model errors out with longer coverage time.

### ISSUE THREAD

**Issue by garnertb** [StatEngine/stat-engine#486]
## Overview
I get an `An error occured running the model.` message when I go from 8 to 13 minutes coverage time.  If there is some upper limit to what the coverage time can be, we should limit the slider to that value.

## Screenshots
![image](https://user-images.githubusercontent.com/1141646/84503600-824f8280-ac88-11ea-92ad-cf6fc94520b5.png)

**Comment by tbuffington7** [comment]
The model runs locally with a coverage time of 50 minutes, so I'm not sure what the issue is
