### ISSUE TITLE
Add jurisdictional boundary to Move up model.

### ISSUE THREAD

**Issue by garnertb** [StatEngine/stat-engine#487]
## Overview
Add the department's jurisdictional boundary from FireCARES to the MUM map to provide the user with more visual context of how much of their jurisdiction is covered.

## Mockups / Screenshots
![image](https://user-images.githubusercontent.com/1141646/84504611-3bfb2300-ac8a-11ea-9129-516d9cd03b81.png)

Add ☝️ to 👇 .

![image](https://user-images.githubusercontent.com/1141646/84504699-61882c80-ac8a-11ea-8eb4-0e8e9ebb80d5.png)

**Comment by bliitzkrieg** [comment]
> same blue stroke as in firecares
