### ISSUE TITLE
Move-up model doesn't populate units for Cape Coral, FL

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#504]
## Overview
Move-up model doesn't appear to be populating for some departments. 

## Environment
-

## Steps to Reproduce
- Switch to Cape Coral, FL
- Go to /move-up-model

![image](https://user-images.githubusercontent.com/32108478/86071506-21130780-ba1b-11ea-9f7f-702b1e5e5218.png)

**Comment by bliitzkrieg** [comment]
Should be resolved once the following PR is merged and the data is reimported.
https://github.com/ProminentEdge/siamese-cape-coral-fl/pull/6
