### ISSUE TITLE
Implement landing page layout for signed-in users

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#61]
Not sure the best way to fit it all, so....

Required
- Link to dashboard loud and clear
- User information and fire department info

Optional
- Plugins/Enrichments enabled for Fire Department
- Table/widget to display the status of data quality.  This is likely 3-10 rows of checks, with either a percentage of incidents violating the rule or indicator describing action needed.

**Comment by chopchop505** [comment]
If you can provide an sketch, we can discuss further.

**Comment by bingles** [comment]
Sounds good, working on this now!

**Comment by bingles** [comment]
Hey @garnertb and @chopchop505, here is the first pass on the landing page - will need some tweaking and validation on assumptions. Happy to discuss when convenient!

![landing_page](https://user-images.githubusercontent.com/636170/35081712-ba5facfc-fbe3-11e7-8c3f-8ff8777c442e.png)

**Comment by bingles** [comment]
@chopchop505 This should be ready for you now. Let me know if you have any questions about the markup or need me to tweak anything as you go through it all!

FYI - I still have to export the final icons for the installed integration cards, but will need to know the list of plugins and enrichments that will be supported.
