### ISSUE TITLE
Implement MarketPlace layout to describe enrichments and plugins

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#62]
Something like: https://github.com/marketplace/codecov.

**Comment by bingles** [comment]
Adding some more examples just for reference, inspiration, and discussion:
- https://stripe.com/works-with
- https://segment.com/catalog
- https://apps.shopify.com/
- https://www.weebly.com/app-center
- https://www.xplenty.com/integrations/
- https://visible.vc/explore/integrations/
- https://hallmonitor.co/integrations
-

**Comment by bingles** [comment]
@garnertb and @chopchop505 Here is the first pass on this landing page. Let me know your thoughts, questions, concerns. 

![marketplace - landing page](https://user-images.githubusercontent.com/636170/35112744-f3809eba-fc4c-11e7-8590-743df1d734d7.jpg)

**Comment by chopchop505** [comment]
Icons for Plugins
- Generic 
- Twitter
- Email Reports
- NFORS 
- DarkSky Weather 
- Census

**Comment by bingles** [comment]
MVP has been pushed to [marketplace](https://github.com/StatEngine/stat-engine/tree/marketplace) branch and is ready for @chopchop505 to work his magic. Will probably need another pass to tighten things up later on at some point.

**Comment by bingles** [comment]
Hey @chopchop505, just a heads up that the detail page has been pushed. The thought is to have the "Integration Settings" block be hidden by default and only be shown when the user is required to input that settings data. 

![marektplace-detail](https://user-images.githubusercontent.com/636170/36108715-b699fdc4-0fda-11e8-81df-6be384d6dff5.png)
