### ISSUE TITLE
Create state-engine landing page logo

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#66]
Could you make a background image for statengine like this spade one?  I'll handle the rest!
![image](https://user-images.githubusercontent.com/32108478/35659541-d8a5e6dc-06aa-11e8-9586-5658a1bade79.png)

**Comment by bingles** [comment]
Here's the first pass with assets attached! :)
![image](https://user-images.githubusercontent.com/636170/36508823-cb0fcce0-172b-11e8-9297-26a1381f0942.png)

**BG**
![statengine-bg](https://user-images.githubusercontent.com/636170/36508837-d75866ce-172b-11e8-94ad-41596b459b87.png)

**Circle Logo**
![se-cirlcle-logo](https://user-images.githubusercontent.com/636170/36508850-ded8b1ec-172b-11e8-9d80-c1b8a9bb0ddd.png)
