### ISSUE TITLE
Create generic icon/graphic for integrations

### ISSUE THREAD

**Issue by bingles** [StatEngine/stat-engine#69]
Would be used on marketplace landing, detail and potentially other views

**Comment by bingles** [comment]
@chopchop505 What about something like this? PS. For some reason the PNG format is grainy, the SVG variant on the current Marketplace is not.

![integration-logo-generic](https://user-images.githubusercontent.com/636170/36000452-f954ea4e-0cf0-11e8-8782-75d27834f281.png)

**Comment by chopchop505** [comment]
looks good
