### ISSUE TITLE
Minor Twitter Changes

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#78]
![image](https://user-images.githubusercontent.com/32108478/36446918-e3e7b3d2-1626-11e8-8c5d-ca432ac0e0db.png)

- [x] Date recommended doesn't look right
- [x] Adjust text wrapping
- [x] Media name should be formatted or removed
- [x] Badge colors should be different for status field

**Comment by garnertb** [comment]
- [ ] Improve iconography (@bingles)
- [ ] Maintain recommendation order after update.  (updating one moved it in the table)
- [ ] Add help text from integration configuration settings.
- [ ] Add media preview from integration config screen?
- [ ] Send from update screen?  I updated a few and forgot to send.

**Comment by chopchop505** [comment]
@garnertb in regards to "Maintain recommendation order after update".  The table shows the last 5 recommended in order of creation, regardless of when they have been updated or tweeted. There was a bug where the date created wasn't right so you probably saw that strange behavior.

Do you think this is sufficient or should we also sort another way?

**Comment by garnertb** [comment]
Yes, that is sufficient.

**Comment by chopchop505** [comment]
`Add media preview from integration config screen` will take more effort than its probably worth at this point

`Send from update screen? I updated a few and forgot to send` I think a wizard might be more appropriate [()](https://github.com/angular-wizard/angular-wizard) ? @bingles what do you think.
