### ISSUE TITLE
Move GA code out of _index.html

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#83]
We probably don't want GA calls occurring for on-premise instances.  
Moving the GA code to an angular aware component will allow us to disable it or make the GA id configurable.

**Comment by garnertb** [comment]
If we're tracking generic user interactions, wouldn't we want both?  Maybe the work here should be to add a flag to allow us to filter out on prem?

**Comment by chopchop505** [comment]
A flag on the call to GA works for me.
I've already made Angular self aware if running in cloud vs on premise so this should be easy.  

Ill add the flag

**Comment by chopchop505** [comment]
I'm assuming the on-premise solution should work without external internet connect, right? 
In that case we obviously wouldn't not get any analytics

**Comment by garnertb** [comment]
I guess it should but most will still have access to the internet.

**Comment by chopchop505** [comment]
Right, I was thinking more of it they installed it in an test or firewalled environment to demo

**Comment by chopchop505** [comment]
OBE as not currently supporting on premise installations
