### ISSUE TITLE
Navigation mockup

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#86]
Mockup to provide navigation to separate pages.  At a minimum....

- Marketplace
- Data quality
- Twitter integrations
- Daily reports

**Comment by bingles** [comment]
@chopchop505 Per our conversation last Friday made some updates to the nav bar. 

![image](https://user-images.githubusercontent.com/636170/38506170-19add22c-3be7-11e8-8445-e440241d2700.png)

![image](https://user-images.githubusercontent.com/636170/38506241-46d674b6-3be7-11e8-812f-eb8f29de00b6.png)

**Comment by chopchop505** [comment]
Great stuff! 
Any stuff on where to put the link to kibana dashboard - should we just treat it as an app (such that theres an icon (next to Daily Reports) and it appears under Dashboards dropdown

**Comment by bingles** [comment]
Thanks! The "Advanced" / Kibana Dashboard is this icon here:  ![image](https://user-images.githubusercontent.com/636170/38526795-aded04ec-3c25-11e8-9871-8b8d30af76b0.png) 

I envision a delayed tooltip for those utility icons, but I like the idea of dropping it under the drop-down menu as well.
