### ISSUE TITLE
Automate welcome message on signup

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#87]
Stephen since you got some mandrill/mailchimp under your belt - lets automate this welcome email.
Please create a new pull request, other than usermanage.  
The base branch can be from usermanage, but I would like to keep it a distinct change. 
  
When a user creates an account, we should send a welcome email.  
There is already a template in Mailchimp (https://us17.admin.mailchimp.com/templates/edit?id=51557).  

@garnertb - feel free to add anything

**Comment by ssontag55** [comment]
@bingles @chopchop505 is there a way to use a mailchimp template for mandrill sties or should I send through mailchimp.

**Comment by chopchop505** [comment]
https://mandrill.zendesk.com/hc/en-us/articles/205583097
